
import React from 'react';
import { GameState } from '../types';

interface RestSummaryProps {
  summaryText: string; // This will be the narrative generated by Gemini for summary
  onConfirm: (confirmed: boolean) => void; // True if confirmed, false if needs correction (advanced)
}

// This component might not be needed if the summary is part of the GameDisplay narrative.
// However, if we want specific UI for summary confirmation, it can be used.
// For now, the summary is handled within the GameDisplay narrative log based on Gemini's output.
// If Gemini sends specific summary structure, GameDisplay can format it.
// The confirmation ("yes/no") is handled by PlayerInput.

const RestSummary: React.FC<RestSummaryProps> = ({ summaryText, onConfirm }) => {
  return (
    <div className="p-4 my-4 bg-gray-700 border border-amber-500 rounded-lg shadow-lg">
      <h2 className="text-xl font-bold text-amber-400 mb-3">End of Day Summary</h2>
      <div className="text-gray-200 whitespace-pre-wrap mb-4" dangerouslySetInnerHTML={{ __html: summaryText.replace(/## (.*?)\n/g, '<h3 class="text-lg text-amber-300 mt-2 mb-1 font-semibold">$1</h3>').replace(/\*\*(.*?)\*\*/g, '<strong class="text-yellow-300">$1</strong>') }} />
      <p className="text-gray-400 mb-3">Is this summary correct?</p>
      <div className="flex space-x-3">
        <button 
          onClick={() => onConfirm(true)}
          className="flex-1 p-2 bg-green-600 hover:bg-green-700 text-white rounded font-semibold transition-colors"
        >
          Yes, Rest for the Night
        </button>
        {/* <button 
          onClick={() => onConfirm(false)}
          className="flex-1 p-2 bg-red-600 hover:bg-red-700 text-white rounded font-semibold transition-colors"
        >
          No, I Need to Correct Something (Advanced)
        </button> */}
      </div>
    </div>
  );
};

export default RestSummary;
// Note: This component is currently illustrative. The summary flow is mostly handled
// by game state transitions and Gemini generating the summary text to be displayed in GameDisplay.
// The PlayerInput component will handle the 'yes'/'no' confirmation.
